### ISSUE TITLE
dynamic obstacles

### ISSUE THREAD

**Issue by boy7307979** [hlx1996/FIESTA#1]
作者您好

Voxblox的这种方法可以允许ESDF的地图动态改变, 使用存储在TSDF中的距离, 而不是从最近的occupied voxel中计算距离. 在原始代码中, 每个voxel有一个占据或者free的状态, 不能改变. voxblox将这个概念改变为around surface fixed band.

想問FIESTA未來會有解決動態環境問題的方法？

**Comment by hlx1996** [comment]
Hello boy7307979,
I am not sure what makes you confused.
The data structure used to represent occupancy in FIESTA is a probabilistic occupancy grid map, which also supports the dynamic obstacles natively.
And since our algorithm only searches from the changed voxels, the updating of ESDF map is still incremental and efficient.

**Comment by boy7307979** [comment]
作者您好
我采用gazebo模拟带有一个溜滑梯的场景
右上框为原本溜滑梯的位置, 后来移动溜滑梯至左下框, 
此時原本右上框的位置已經是空的了,重新对它进行观测时, 希望能culling掉它
以probabilistic occupancy grid map的架构能够实现吗？
![image](https://user-images.githubusercontent.com/5019568/61943943-211ab400-afcf-11e9-9589-e9b6a639e0b9.png)

**Comment by hlx1996** [comment]
It the slide in the top-right rectangle disappears due to some reason when observing back there, the probabilistic occupancy grid map can finish this work natively, by step-by-step reduce the probability. If you want to change the changing velocity and stability, parameters like `p_miss` may help you.

If you want to deal with the error caused by drifted localization systems, you can try to change the `global_map` parameter to `false`.

**Comment by USTfgaoaa** [comment]
@boy7307979 
Of course, a probabilistic occupancy grid map can deal with that.
The probabilistic occupancy grid map is a dynamic mapping structure, it can dynamically update/eliminate obstacles within the map. 
There is no fundamental difference between 'Fiesta' and 'Voxblox' while dealing with dynamic environments.
I guess you can read the paper.
If your question is answered, please close the issue.

**Comment by boy7307979** [comment]
好的，謝謝兩位作者回答
